/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "mcpdb-vpc": {
      "type": "sst.aws.Vpc"
    }
    "web": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
  }
}
